version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "2335:2335"
    volumes:
      - .:/app
    env_file:
        - .env

    command: tail -f /dev/null

